
import { jsPDF } from 'jspdf';
import { ScoreCard } from '../types';

export const generatePerformanceReport = (candidateName: string, cohortName: string, scoreCards: ScoreCard[]) => {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString();

  // -- Header --
  // Blue Header Bar
  doc.setFillColor(37, 99, 235); // Blue-600
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("CAPACITI Talent Hub", 20, 20);
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("Performance Progress Report", 20, 30);

  // -- Candidate Details --
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(12);
  
  doc.text(`Candidate Name: ${candidateName}`, 20, 55);
  doc.text(`Cohort: ${cohortName}`, 20, 62);
  doc.text(`Report Date: ${date}`, 20, 69);

  // -- Summary Stats --
  const avgAttendance = Math.round(scoreCards.reduce((acc, curr) => acc + curr.attendance, 0) / scoreCards.length) || 0;
  const avgTech = Math.round(scoreCards.reduce((acc, curr) => acc + curr.techSkills, 0) / scoreCards.length) || 0;
  const avgDelivery = Math.round(scoreCards.reduce((acc, curr) => acc + curr.objectDelivery, 0) / scoreCards.length) || 0;

  doc.setFillColor(245, 247, 250); // Light Gray bg
  doc.rect(20, 80, 170, 30, 'F');
  
  doc.setFont("helvetica", "bold");
  doc.text("Overall Averages", 30, 92);
  
  doc.setFont("helvetica", "normal");
  doc.text(`Attendance: ${avgAttendance}%`, 30, 102);
  doc.text(`Tech Skills: ${avgTech}%`, 90, 102);
  doc.text(`Delivery: ${avgDelivery}%`, 150, 102);

  // -- Detailed Table --
  let yPos = 130;
  
  // Table Header
  doc.setFillColor(30, 41, 59); // Slate-800
  doc.setTextColor(255, 255, 255);
  doc.rect(20, yPos, 170, 10, 'F');
  doc.setFontSize(10);
  doc.text("Week", 25, yPos + 7);
  doc.text("Date", 45, yPos + 7);
  doc.text("Attendance", 75, yPos + 7);
  doc.text("Tech Score", 105, yPos + 7);
  doc.text("Reviewer", 135, yPos + 7);

  yPos += 10;
  doc.setTextColor(50, 50, 50);

  scoreCards.forEach((card, index) => {
    // Row Bg (zebra striping)
    if (index % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(20, yPos, 170, 10, 'F');
    }
    
    doc.text(`W${card.week}`, 25, yPos + 7);
    doc.text(card.date, 45, yPos + 7);
    doc.text(`${card.attendance}%`, 75, yPos + 7);
    doc.text(`${card.techSkills}%`, 105, yPos + 7);
    doc.text(card.reviewerName, 135, yPos + 7);
    
    yPos += 10;
  });

  // -- Footer --
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by CAPACITI Intelligent Talent Hub System", 20, 280);

  doc.save(`${candidateName.replace(' ', '_')}_Progress_Report.pdf`);
};